export { default as Header } from './Header'
export { default as About } from './About'
export { default as Speeches } from './Speeches'
export { default as Stages } from './Stages'
export { default as Previous } from './Previous'
export { default as FAQ } from './FAQ'
export { default as Marks } from './Marks'
export { default as Footer } from './Footer'
